# Generated by Django 3.1.6 on 2021-02-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w', models.CharField(max_length=255)),
                ('x', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='domain',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
