# Generated by Django 3.1.6 on 2021-02-08 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210208_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
