# Generated by Django 3.1.6 on 2021-02-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20210208_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='freq',
            field=models.IntegerField(default=0),
        ),
    ]
